export const CHANGE_CITY = 'CHANGE_CITY';
export const CITY_NOT_FOUND = 'CITY_NOT_FOUND';
export const CITY_DATA = 'CITY_DATA';
export const WEATHER_DATA = 'WEATHER_DATA';
export const TEMP_FAHRENHEIT = 'TEMP_FAHRENHEIT';
export const TOGGLE_TEMP = 'TOGGLE_TEMP';
export const TOGGLE_LOADER_FAHRENHEIT = 'TOGGLE_LOADER_FAHRENHEIT';
export const TOGGLE_LOADER_MAIN = 'TOGGLE_LOADER_MAIN';
